### ISSUE TITLE
Update example next.config.js

### ISSUE THREAD

**Issue by dev-chulbuji** [danielcondemarin/serverless-nextjs-plugin#3]
example have to get serverless target
```
const withCSS = require("@zeit/next-css");
module.exports = withCSS({
  target: "serverless",
  assetPrefix: "https://s3.amazonaws.com/{myBucket}"
});
```

here is error stack
```
Error: Serverless Nextjs: Target 'server' is invalid. Set 'serverless' as the target
    at createError (/Users/dj/project/nextjs/serverless-nextjs-plugin/examples/basic-next-serverless-app/node_modules/serverless-nextjs-plugin/utils/createError.js:2:10)
    at module.exports.nextConfigDir (/Users/dj/project/nextjs/serverless-nextjs-plugin/examples/basic-next-serverless-app/node_modules/serverless-nextjs-plugin/lib/parseNextConfiguration.js:20:11)
    at ServerlessNextJsPlugin.get configuration [as configuration] (/Users/dj/project/nextjs/serverless-nextjs-plugin/examples/basic-next-serverless-app/node_modules/serverless-nextjs-plugin/index.js:47:12)
    at nextBuild.then (/Users/dj/project/nextjs/serverless-nextjs-plugin/examples/basic-next-serverless-app/node_modules/serverless-nextjs-plugin/index.js:57:44)
From previous event:
    at PluginManager.invoke (/Users/dj/n/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/Users/dj/n/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at Deploy.BbPromise.bind.then (/Users/dj/n/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/dj/n/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/dj/n/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/Users/dj/n/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.run (/Users/dj/n/lib/node_modules/serverless/lib/classes/PluginManager.js:438:17)
    at variables.populateService.then.then (/Users/dj/n/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Serverless.run (/Users/dj/n/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/Users/dj/n/lib/node_modules/serverless/bin/serverless:43:28)
    at /Users/dj/n/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/dj/n/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at initializeErrorReporter.then (/Users/dj/n/lib/node_modules/serverless/bin/serverless:43:6)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at /Users/dj/n/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/Users/dj/n/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by danielcondemarin** [comment]
@dev-chulbuji Thanks for reporting! The example was using an old version of the plugin so I've updated it. The newer version automatically sets the target to "serverless" for you 👍
