### ISSUE TITLE
Cannot use deploymentBucket in serverless.yaml

### ISSUE THREAD

**Issue by mattdell** [danielcondemarin/serverless-nextjs-plugin#55]
I want to keep my serverless deployments in one bucket, as supported by [the serverless.yaml docs](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml)

When I add 

```
  deploymentBucket:
    name: myBucketName
```

I get the following error and stack trace:

```
Type Error ---------------------------------------------
 
  Cannot read property 'Resources' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'Resources' of undefined
    at addS3BucketToResources (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless-nextjs-plugin/lib/addS3BucketToResources.js:24:6)
From previous event:
    at PluginManager.invoke (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.spawn (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at Deploy.BbPromise.bind.then (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/Serverless.js:109:33)
    at processImmediate (timers.js:638:19)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Serverless.run (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/lib/Serverless.js:96:6)
    at serverless.init.then (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/bin/serverless:43:28)
    at /Users/me/Work/Repos/myApp.front-end/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/me/Work/Repos/myApp.front-end/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at initializeErrorReporter.then (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/bin/serverless:43:6)
    at processImmediate (timers.js:638:19)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at /Users/me/Work/Repos/myApp.front-end/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/Users/me/Work/Repos/myApp.front-end/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

The unhappy code lives in addS3BucketToResources.js: in serverless-nextjs-plugin/lib.

It's not clear to me what's happening, but somehow `cf` becomes undefined on this line:

```
cf.Resources.NextStaticAssetsS3Bucket.Properties.BucketName = bucketName;
```

I'd appreciate any insight, advice, or solutions!

**Comment by danielcondemarin** [comment]
Hi @mattdell can you try again with [v1.8.0](https://github.com/danielcondemarin/serverless-nextjs-plugin/releases/tag/v1.8.0). I did some changes around how the S3 bucket is managed that might have fixed this.

**Comment by mattdell** [comment]
Hmm. Not quite there yet.

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless Nextjs: Cleaning up tmp build folder ...
Serverless Nextjs: Found bucket "<my bucket>"
 
  Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           11.12.0
     Serverless Version:     1.41.1
```

Strange messaging

* Found bucket
* Could not locate bucket

🤔

**Comment by saadtazi** [comment]
The following settings worked for us, as stated in the documentation:
```
myNextApp:
  component: serverless-next.js
  inputs:
    bucketName: my-bucket-name
```
I think you're not supposed to have a `provider` root section in the yaml file.
